.INTEL
npwhrindia@intel.com
BangaloreORACLE
naveen.vemula@oracle.com
suman.rajeev@oracle.comBangaloreLUCENT
hrindia@lucent.com
BangaloreSONY
dreamjob@sisc.in.sony.com.sg
Bangalore
SingaporeHUGHES
hsshr@hss.hns.com
Delhi
Bangalore
NORTEL
nadhr@nortelnetworks.comTCS
recruitment@blore.tcs.co.in
BangaloreVeritas
bangalore@vxindia.veritas.com
Unix
BangaloreAspect
Dev
jobs@india.aspectdv.com
Ecom
BangaloreMBT
resume@mahindrabt.com
PuneHP
resumes@india.hp.com
BangaloreHCL
Tech
rsriram@hclt.comPENTAFOUR
muralikrishna@pentafour.com
NOVELL
career@novell.com
BangaloreSUN
careers@india.sun.com
Bangalore


BPL Innovision
 -
 jobs@bplinnovision.comD
 E
 Shaw
 -
 recruit-india@deshaw.com
 HyderabadiCode
 -
 hr_india@icode.comPTPL
 -
 prakash@ptpl.comInfoGain
 hrdindia@india.infogain.com
 DelhiSatyam
 globaltalent@bet.satyam.com
 BangalorePSI
 resumes@psi.soft.net
 BangaloreStumpVision
 stumpvision@blr.vsnl.net.in
 krish@stumpvision.comInfosys
 bangalore.hrd@inf.comSiemens
 hmsrecruit@sisl.co.in
 BangaloreWipro
 careers@wipro.com
 BangaloreAmerican
 Data
 Solutions
 adsihr@gafri.com
 BangaloreHealtheon
 jobs@healtheonindia.comHCL
 Tech
 resumeblr@hclt.comBharti
 Telesoft
 careers@bhartitelesoft.comIBM
 osudar@in.ibm.com
 mamol@in.ibm.comFor
 Lucent
 skg@spectrumconsultants.comGE
 India
 itl.geitc@geind.ge.com
 BangaloreiCope
 hrd@icope.com
 Wireless
 NATIONAL
 careers@malkauns.nsc.com
 Embedded

Philips
 pscareers2000@philips.com
 EmbeddedBOSCALLEO
 hr@boscalleo.com
 EcommIT
 Solutions
 careers_2000@its.soft.netHCL
 Tech
 careerb@msdc.hcltech.com
 NIHILENT
 career@nihilent.comInfosys
 careers@inf.comCISCO
 india_jobs@cisco.com
 NetworkingPEOPLE.COM
 speri@techpeople-india.com
 US
 NetBrahma
 Want2b@netbrahma.com
 SystemsSunCoreSoft
 hrd@suncoresoft.comIshoni
 jobs@ishoni.comLG
 Software
 I
 walkin@lgsi.com
 Ecom
 ,
 EmbeddedHPS
 Global
 hps.rmg@hpsglobal.comReliance
 ,
 US
 jobs@reliance.comESCOSOFT
 carer@escosoft-tech.com
 USSERANOVA
 careerindia@seraova.com
 EcomTeleSoft
 hrd@indts.com
 TelecomSSI
 infinity@ssi-technologies.com
 BangaloreMelStar
 bstp@melstar.com
 Bombay
 ChennaiUSInteractive
 careers@usinteractive.com
 US

Cerebra
 jobs@cerebracomputers.comEmpowertel
 hrindia@empowertel.comPTC
 hrtoi@india.ptc.com
 PUNESiri
 Technolgoies
 hr@siritech.comALIT
 hr@alit.soft.neti-Flex
 sandeep.bhattacharya@iflexsolutions.comCosmoNet
 hrd@cosmonetsolutions.comPOLARIS
 resume_toib@polaris.co.inRAS
 Infotech
 resumes@rasinfotech.comSIP
 Technolgies
 hrd@siptech.co.inSNS
 Tech
 careers@snstech.comAUTODESK
 crvcon@vsnl.comLGSoft
 onsite_java@lgsi.comKindle
 work_here@kindlesystems.com
 PUNE
 US
 UKInfoStrands
 infostrands@gtvltd.comObjectOrb
 hr@objectorb.comComnet
 hrd@comneti.com
 telecomCIS
 hrtelecom@cisindia.comOnwardGroup
 geetha_cherian@onwardgroup.comGreen
 Microsystems
 jobs@greenmicrosystems.com

STPI
 personnel@stpb.soft.netQuark
 careers@quark.stpm.soft.net
 MOHALIDelDot
 subbu@deldot.comSUBEX
 ganesh@subegroup.comSIERRAOPT
 career@sierraopt.comDSQ
 recruit_ecom@md.in.dsqsoft.com
 CHENNAIIIC
 hr@iictechnologies.comCYBERTECH
 ecomjobs@cybertech.comFormulaSys
 resumes@FormulaSys.com
 USWorkFlow
 hr@workflow.comSystemLogic
 got2b@SystemLogic.comCyberAnalysts
 resume@cyberanalysts.comIMPETUS
 hr@impetus.co.in
 INDOREVISTEON
 svadivel@VISTEON.com
 EMBEDDEDAmadee
 myjobs@amadee.de
 INTERNETWEBTEK
 webtek_jobs@dresdner-bank.comCIRRUS
 LOGIC
 hrd@cirrus.stpp.soft.netTCS
 Chennai
 resume@chennai.tcs.comTVSFUGEN
 mjojo@tvsfugen.comOnscan
 -Wireless
 -
 jobs@onscan.com

EmbeddedWireless
 jobs@EmbeddedWireless.comDECCANET
 career@deccanetdesigns.comDuskValley
 joinus@DuskValley.com
 duskvalley@vsnl.com
 INTERNETSEMA
 hrd@sema.co.in
 CALCUTTA
 TElecomFTD
 future4u@ftdpl.com.sg
 DSP
 /
 TelecomSAS
 careers@sasi.comSPIKE
 design@spikeindia.soft.net
 EDA
 /
 ASICHCL
 freedom@ggn.hcltech.comAptech
 corporatetrg@aptech.co.inDatamatics
 psaib@datamatics.com
 BOMBAYAQUILA
 hrd@aquila.soft.net
 Graphics
 ,
 EBusinessDATUM
 careers@datumtec.comHUGHES
 resumetoib@hss.hns.comAMBER
 india_jobs@ambernetworks.com
 NetworkingIntegra
 career@integramicro.comLante
 cvindia@lante.com
 DELHI
 -EcomRELQ
 RELQusa@RELQ.comSonata-US
 hrd@sonata-software.com
 career@sonata-software.comZAP
 hrdbg@skillsandjobs.comZensar
 dreamcareers@zensar.com

Spectrum
 ,
 Singapore
 ravikum@mbox2.singnet.com.sgForbes,
 UK
 forbeshr@bgl.vsnl.net.in
 forbesbg@bgl.vsnl.net.inSynopsys
 guru@synopsys.comJobCurry
 Australia
 map@jobcurry.comSingapore,
 UNIX
 cn66@vsnl.comSun
 Tech
 US
 hr@suntechnologies.comHCL
 Tech
 -
 careers@noida.hclt.com
 NoidaInfosys
 -
 engserv@inf.comHTC
 -
 htc.blr@htcinc.comCGSmith
 -
 resume@cgs.cgsmith.soft.netAPCC
 -
 irecruit@apcc.comTechDrive
 sunitha@techdriveintl.comUniqueComputing
 careers@uniquecomputing.com
 USAccord
 Soft
 asiapacific@accord-soft.comZenSoft
 hrd.zensoft@pacific.net.sg
 SingaporeZenith
 hr@zenithsoft.com
 MumbaiVelocient
 rsg@in.velocient.com
 Delhi
 ,
 USSelectica
 hr_bgl@selectica.comThink
 Inc.
 jobs@thinkbn.com
 Coimbatore
 -Mphasis
 hr@mphasis.com

Digital
 di.recruit@digital.comAlopa
 hrindia@alopa.comSilicon
 Automation
 Systems
 careers@sasi.comBirla
 Software
 recruitment@birlasoftware.comWebXL
 jobs@webxl.comTalisma
 got2b@talisma.comAditi
 got2b@aditi.com
 want2b@aditi.comAmSoft
 hrd@amsoftis.comBangalore
 Software
 jobs@bangaloresoftware.comARTHUR
 ANDERSEN
 rescw@arthurandersen.comRaffles
 careers@raffles.soft.netECosmos
 hr_ecosmos@netkracker.comSAP
 sanjukta.sarkar@sap.comPUNDITS
 protocol@pundits.comAZTEC
 jobs@aztecsoft.comInfy
 Banking
 Software
 banking_hrd@infy.comInfy
 IS
 Software
 careers.IS@inf.comHPS(Perot)
 Global
 opportunities@hpsblr.soft.netCSS
 jobs@csshome.netCBSI
 recruiting@cbsinc.com


 NetGalactic
  hr@netgalactic.comOrbit-e
  livefree@orbit-e.comis3c
  hr@is3c.comTenet
  jobs@tenetindia.comGMR
  Info
  opportunities@gmrinfo.comIntergraph
  resume_india@intergraph.com
  Net-Kraft
  be@net-kraft.comHoneywell
  career@hiso.honeywell.comTEIL
  hrssg@teil.soft.netCMG
  careers@cmg.nuCMC
  hrd@blr.cmc.net.inComInsights
  general@cominsights.comMultiTech
  -
  resume@multitech.co.inPlacement
  Companies
  :infdim@vsnl.comReach
  Consulting
  reach@vsnl.comrebus@vsnl.com
  NexAge
  Consulting
  -
  jobs@nexageconsulting.comiihmr@iihmr.orgibelong@zeenext.com

JK
 Consultants
 jkconsultants@vsnl.comloginjobs@vsnl.cominfdim@vsnl.com
 pdotblr@usa.netanil.ballari@indusconsultants,comConsulti
 consulti@vsnl.commsindinc@aol.comvma@vsnl.com
 Wirelesscareers@inficompsys.comresumes@sysprotech.comcareerindia@satyamonline.comcareerindia@123india.comresoft@satyam.net.insixsigma@bgl.vsnl.net.inPlacement
 Companies
 :infdim@vsnl.comReach
 Consulting
 reach@vsnl.comrebus@vsnl.com
 NexAge
 Consulting
 -
 jobs@nexageconsulting.comiihmr@iihmr.orgibelong@zeenext.comJK
 Consultants:
 jkconsultants@vsnl.com


loginjobs@vsnl.cominfdim@vsnl.com
 pdotblr@usa.netanil.ballari@indusconsultants,comConsulti:
 consulti@vsnl.commsindinc@aol.comvma@vsnl.com
 Wirelesscareers@inficompsys.comresumes@sysprotech.comcareerindia@satyamonline.comcareerindia@123india.comresoft@satyam.net.insixsigma@bgl.vsnl.net.inRegards